### ISSUE TITLE
Issues using this 

### ISSUE THREAD

**Issue by michaelwapp** [m-ripper/jovo-plugin-class-handler#1]
Hi!

I tried using this package but I couldn't get it to work. 

My project uses the following Jovo versions: 

```
Jovo CLI Version: 2.2.7

Jovo packages of current project:
  jovo-cms-i18next: 2.2.9
  jovo-core: 2.2.8
  jovo-db-filedb: 2.2.8
  jovo-framework: 2.2.11
  jovo-platform-alexa: 2.2.13
  jovo-platform-dialogflow: 2.2.9
  jovo-platform-googleassistant: 2.2.11
  jovo-plugin-class-handler: 1.2.0
  jovo-plugin-debugger: 2.2.9

```

I followed the README but when executing ```tsc``` the following two errors are triggered:

```
node_modules/jovo-platform-googleassistant/dist/src/index.d.ts:43:15 - error TS2430: Interface 'GoogleAction' incorrectly extends interface 'Jovo'.
  Types of property 'ask' are incompatible.
```
and
```
node_modules/jovo-platform-googleassistant/dist/src/core/GoogleAction.d.ts:13:5 - error TS2416: Property 'ask' in type 'GoogleAction' is not assignable to the same property in base type 'Jovo'.
```

Do you know whats going on? 

Cheers, Michael

**Comment by Veake** [comment]
Hello Michael, 
thanks for trying out this package. 

I have looked into the issue and found out that there currently is a typing problem that occurs with the ```jovo-platform-googleassistant```, that means that this issue should occur without my plugin as well. 

As a possible fix you could do the following: (although it should only be a temporary solution until the issue was fixed inside ```jovo-platform-googleassistant```)

Somewhere in your project, for example inside the ```app.ts``` add the following block:
```
declare module 'jovo-platform-googleassistant' {
    interface Jovo {
        ask(
            speech: string | SpeechBuilder | string[],
            reprompt: string | SpeechBuilder | string[],
            ...reprompts: Array<string | SpeechBuilder>
        ): this
    }
}
```
With this block being added, you should be able to compile with tsc.

Let me know if you have any questions or this approach did not help.
Greetings, Max

**Comment by Veake** [comment]
Hello Michael,
first of all thanks for trying out this plugin.

I have looked upon the issue and found out that there currently is a typing-problem inside ```jovo-platform-googleassistant```. I have tried several ways to augment the ```Jovo``` type but without success.

Sadly this means that you cannot use ```jovo-platform-googleassistant``` until it was fixed. 
I would recommend you to test with Alexa if that makes sense to you. 

I will close this issue as soon as ```jovo-platform-googleassistant``` was updated.

**Comment by Veake** [comment]
I forgot to mention, that you can alternatively set ```skipLibCheck: true``` in your ```tsconfig.json``` and these errors will be ignored but obviously this will ignore other errors which can cause problems.

**Comment by michaelwapp** [comment]
Okay, thanks for your answer. I will watch this issue and check back when its fixed.

**Comment by m-ripper** [comment]
Today, I have upgraded the package to support the latest version of the jovo-framework.
The issues have been fixed.
